packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@reown/appkit': true
  esbuild: true
  keccak: true
overrides:
  '@wagmi/connectors': 8.1.0
  vue: 3.5.41
  vue-router: 5.2.0
