import {
  arbitrum,
  base,
  baseSepolia,
  bsc,
  mainnet,
  polygon,
} from '@reown/appkit/networks'
import { Asset } from './index'

export type EvmAsset = Asset & {
  namespace: 'eip155'
}
export const assets: EvmAsset[] = [
  {
    name: 'Tether',
    symbol: 'USDT',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdt.png',
    address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    chain: {
      id: mainnet.id,
      name: mainnet.name,
      shortName: mainnet.nativeCurrency.symbol,
      color: '#627EEA',
    },
  },
  {
    name: 'Tether',
    symbol: 'USDT',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdt.png',
    address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    chain: {
      id: polygon.id,
      name: polygon.name,
      shortName: polygon.nativeCurrency.symbol,
      color: '#8247E5',
    },
  },
  {
    name: 'Tether',
    symbol: 'USDT',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdt.png',
    address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
    chain: {
      id: arbitrum.id,
      name: arbitrum.name,
      shortName: arbitrum.nativeCurrency.symbol,
      color: '#97adce',
    },
  },
  {
    name: 'Tether',
    symbol: 'USDT',
    namespace: 'eip155',
    decimals: 18,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdt.png',
    address: '0x55d398326f99059ff775485246999027b3197955',
    chain: {
      id: bsc.id,
      name: bsc.name,
      shortName: bsc.nativeCurrency.symbol,
      color: '#F3BA2F',
    },
  },
  {
    name: 'Tether',
    symbol: 'USDT',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdt.png',
    address: '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2',
    chain: {
      id: base.id,
      name: base.name,
      shortName: base.nativeCurrency.symbol,
      color: '#0052FF',
    },
  },
  // {
  //   name: 'Tether',
  //   symbol: 'USDT',
  //   namespace: 'eip155',
  //   decimals: 6,
  //   icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdt.png',
  //   address: '0x323e78f944A9a1FcF3a10efcC5319DBb0bB6e673',
  //   chain: {
  //     id: baseSepolia.id,
  //     name: baseSepolia.name,
  //     shortName: baseSepolia.nativeCurrency.symbol,
  //     color: '#0052FF',
  //   },
  // },
  {
    name: 'Circle USD Stablecoin',
    symbol: 'USDC',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdc.png',
    address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    chain: {
      id: mainnet.id,
      name: mainnet.name,
      shortName: mainnet.nativeCurrency.symbol,
      color: '#627EEA',
    },
  },
  {
    name: 'Circle USD Stablecoin',
    symbol: 'USDC',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdc.png',
    address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    chain: {
      id: base.id,
      name: base.name,
      shortName: base.nativeCurrency.symbol,
      color: '#0052FF',
    },
  },
  {
    name: 'Circle USD Stablecoin',
    symbol: 'USDC',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdc.png',
    address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    chain: {
      id: arbitrum.id,
      name: arbitrum.name,
      shortName: arbitrum.nativeCurrency.symbol,
      color: '#97adce',
    },
  },
  {
    name: 'Circle USD Stablecoin',
    symbol: 'USDC',
    namespace: 'eip155',
    decimals: 6,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdc.png',
    address: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
    chain: {
      id: polygon.id,
      name: polygon.name,
      shortName: polygon.nativeCurrency.symbol,
      color: '#8247E5',
    },
  },
  {
    name: 'Circle USD Stablecoin',
    symbol: 'USDC',
    namespace: 'eip155',
    decimals: 18,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/usdc.png',
    address: '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
    chain: {
      id: bsc.id,
      name: bsc.name,
      shortName: bsc.nativeCurrency.symbol,
      color: '#F3BA2F',
    },
  },
]
